### ISSUE TITLE
Create a variable file at <openshift4-deploy>/vars/ocp4.yml.

### ISSUE THREAD

**Issue by mflannery** [jaredhocutt/openshift4-deploy#28]
When I execute openshift-deploy shell I am placed into a shell environment which does not have the ~/openshift-deploy/* directories within. In this shell I don't have a vars directory and no ocp4.yml file.  If I am outside of the openshift-deploy shell, I do have a vars directory and an ocp4.example.yml file.  Should I create the ~/vars/ocp4.yml file while I am in the openshift-deploy shell or outside of the shell?

Mike

**Comment by mflannery** [comment]
I don't know what went wrong the first time but running this a SECOND time and I can see all the directories and files.

**Comment by jaredhocutt** [comment]
The script that you're running that creates the shell takes the directory where that script lives, which should be the base `openshift4-deploy` directory and maps it to `/app` in the container where the shell is running.

I haven't seen this happen myself, but if you happen to reproduce at some point, let me know so I can figure out what might be causing it.

Thanks @mflannery
