### ISSUE TITLE
In step 3, if you create the key and download the PEM file the permissions on the file need to be 400

### ISSUE THREAD

**Issue by mflannery** [jaredhocutt/openshift4-deploy#30]
In Step 3

IMPORTANT: The key pair .pem file should be in ~/.ssh as this directory gets mounted to the environment for you. 

Add

This file also needs 400 permissions (or however you want to see read for current user only).

**Comment by johnsimcall** [comment]
@jaredhocutt PR #33 from our previous Google Meet collab session dropped this fix, so I restored it, and made a second commit.  Please review at your convenience and consider rejecting PR #31
