### ISSUE TITLE
 'dict object' has no attribute 'public_ip_address'

### ISSUE THREAD

**Issue by nnachefski** [jaredhocutt/openshift4-deploy#46]
Ran through a basic AWS (not GovCloud) install and got this error:

```
TASK [infrastructure : Add bastion to inventory] ***********************************************************************************************************************************************************************************************************
Wednesday 24 June 2020  21:34:03 +0000 (0:00:02.644)       0:06:32.411 ********
fatal: [localhost]: FAILED! => {}

MSG:

The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'public_ip_address'

The error appears to be in '/app/playbooks/roles/infrastructure/tasks/aws_info.yml': line 9, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Add bastion to inventory
  ^ here

```

**Comment by jaredhocutt** [comment]
I've had this happen to me once before, but it worked after running it again.

My guess is that it's a race condition on the AWS side where it doesn't always return the correct data just after things are created, especially when elastic IPs are used.

Thanks for reporting this! I'll take a look at adding some retries or finding a more reliable way to ensure that data gets returned.

**Comment by nnachefski** [comment]
I've tried several times with the same result.  It appears that everything is getting provisioned correctly.  Instances get provisioned and are up.  Bastion gets assigned an EIP.  ELBs are provisioned with Targetgroups, but i dont see any listeners assigned to any of them.  Maybe listener creation occurs later and this error is preventing that.

**Comment by jaredhocutt** [comment]
@nnachefski Hmm, that's weird. The target groups should be there and populated with the instances. If you have some time next week, I'd love to jump on a screenshare and debug.

**Comment by nnachefski** [comment]
@jaredhocutt I'm available whenever you are this week.  Let me know when and we can jump on a screenshare.

**Comment by jaredhocutt** [comment]
@nnachefski I'll shoot you an email to coordinate.

**Comment by jaredhocutt** [comment]
@nnachefski and I jumped a screenshare and were able to get a successful deployment. Unfortunately, this means we weren't able to reproduce the issue above.

For now, I'm going to close this issue, but if you run into the same issue again, please open this back up and let's take another look.

**Comment by johnsimcall** [comment]
We identified root-cause for this.  It only appears when re-running the create playbook shortly after destroying the previous AWS resources.  In this situation the Ansible task to query the "bastion" instance's info (including public_ip_address) returns the info from the terminated instance, instead of the the new running instance.  We will update the task so that it ignores any terminated instances.
